apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-__BRANCH__
  namespace: argocd
spec:
  project: namespace-pattern
  source:
    repoURL: https://github.com/MasayaAoyama/pull-request-kubernetes.git
    targetRevision: __BRANCH__
    path: manifests/app/
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: __BRANCH__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
