apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-cd-__BRANCH__
  namespace: argocd
  labels:
    branch: __BRANCH__
spec:
  project: namespace-pattern
  source:
    repoURL: https://github.com/MasayaAoyama/pull-request-kubernetes.git
    targetRevision: __BRANCH__
    path: manifests/app/
    kustomize:
      {} # image: masayaaoyama/demo-app:__BRANCH__
  destination:
    server: https://kubernetes.default.svc
    namespace: __BRANCH__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
