apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefix-cd-__BRANCH__
  namespace: argocd
spec:
  project: prefix-pattern
  source:
    repoURL: https://github.com/MasayaAoyama/pull-request-kubernetes.git
    targetRevision: __BRANCH__
    path: manifests/app/
    kustomize:
      nameSuffix: __BRANCH__
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
