apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-master
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasayaAoyama/pull-request-kubernetes.git
    targetRevision: master
    path: manifests/app/
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
